name: Governance review request
description: Ask for a governance review for your project from TAG Contributor Strategy
title: "[Governance Review]: PROJECT NAME"
labels: ["wg/governance"]
projects: ["cncf/25"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in having a governance review request from TAG Contributor Strategy. 
        For more information on what a governance is, please visit our [governance documentation](https://contribute.cncf.io/maintainers/governance/overview/).

  - type: input
    attributes:
      label: Project Name
    validations:
      required: true

  - type: input
    attributes:
      label: Project Website
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Please provide at least 2 people who are able to help us understand the governance of your project, in case there is material that is not clear.

  - type: input
    attributes:
      label: Contact Details 1
      placeholder: ex. @githubHandle
    validations:
      required: true
  - type: input
    attributes:
      label: Contact Details 2
      placeholder: ex. @githubHandle
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Reason for governance review request
      description: |
        What is the reason for your governance review request? This will help us understand the context of your request,
        help us prioritize it and also help us understand what you are looking for from the review.
      options:
        - (please select)
        - CNCF Sandbox acceptance application
        - Application for moving levels from Sandbox to Incubation
        - Application for moving levels from Incubation to Graduation
        - Other (please specify in the “Additional Notes” input at the end of this form)
      default: 0
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        ## Documentation

  - type: textarea
    attributes:
      label: Governance model
      description: |
        If your project governance is based on one of the [CNCF governance templates](https://contribute.cncf.io/maintainers/templates/governance-intro/), 
        please indicate which one it is here, with any differences for your project.
        If not, please write a short description of your governance model.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional notes
      description: Please add any additional notes here.
